### ISSUE TITLE
How to include custom classes/services in controllers

### ISSUE THREAD

**Issue by Cecildt** [zekelevu/typeframework#1]
Hi,

Great framework!

What would be the best way be to include a custom class/service in a controller. Let's say I want to create a Azure class to abstract away the Azure API from my controllers.

Thanks!

**Comment by zekelevu** [comment]
Thank you, Cecildt

Do you mean like adding a helper or util class? If that's the case you can just add it to the `/app` folder and reference it in the `app.ts`. Make sure you reference it before all the controllers so that it can be accessed by them.

**Comment by Cecildt** [comment]
Thanks for the help. Also I was considering a good folder structure for helper classes or services. For now I added a services folder under the app folder and references in app.ts. My playing project for the framework: https://github.com/Cecildt/azure-blogger/
