### ISSUE TITLE
Add tfw watch command

### ISSUE THREAD

**Issue by Cecildt** [zekelevu/typeframework#3]
Hi Zeke,

Feature request: Can you please add a "tfw watch" command that will basically use grunt watch to compile .ts files on file changes and restart the app?

Thanks!

**Comment by zekelevu** [comment]
Hi @Cecildt, I'm considering adding something like that. What do you think about `tfw start --watch`

**Comment by Cecildt** [comment]
That would be perfect. Thanks!
