### ISSUE TITLE
Testing with Mocha

### ISSUE THREAD

**Issue by Cecildt** [zekelevu/typeframework#4]
Hi,

I need some guidance on creating mocha tests for a Typeframework application. How do I access the controllers and other objects from the app.js file in a test? Can you please provide an example?

Thanks!

**Comment by zekelevu** [comment]
I haven't really thought of the best way of doing this. But one way would be using node module `exports` to do this. For example on `app.ts`:

```
exports.MyController = MyController
```

then on your test file:

```
var myController = require('app.js').MyController
```

**Comment by arealmaas** [comment]
Does this work? Trying with Jasmine and dupertest, but i get an error stating that the "json" and "view" functions are not in the controller. Seems like you have to spin up a server then?
