### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by leslyarun** [zekelevu/typeframework#8]
I don't find any latest updates. Is the project actively maintained ?

**Comment by daslicht** [comment]
Same question here

**Comment by jwuliger** [comment]
I think its dead... :-1:

**Comment by daslicht** [comment]
ok guys :) either we move on or create something new :)

**Comment by jwuliger** [comment]
Yeah. It's too bad. It was a solid project.

**Comment by mii9000** [comment]
I think this project has potential. I would use it even if it gets dumped. Maybe someone capable can adopt it?

**Comment by daslicht** [comment]
I would be carefull if you are not able to maintain it yourself. What happens if in future something gets deprecated ... :)

**Comment by jhonmike** [comment]
I'll try to do something for the project!

**Comment by jhonmike** [comment]
hello, I could not contact @zekelevu

so I created https://github.com/tsframework

and updated the maximum as possible

it is functional

```
npm install tsfw-cli -g
tsfw new apptest
cd apptest
npm install
grunt
node .build/app.js
```

obs.: If @zekelevu return to active, we can merge!
